### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by pranjaldhole** [yapic/napari-yapic-prediction#3]
## Current behaviour

Single progress bar iterating twice for prediction and upload

## Expected behaviour

Two progress bars:
1. `Predicting` image segmentation maps 
2. `Uploading` layers to napari

**Comment by dlesmesl** [comment]
Hello Pranjal,

In this pull request #4 you can see the implementation of a second progerss bar to the widget, in this way the users have a better idea of the full prediction progress.

**Comment by pranjaldhole** [comment]
commit #8c3e01b8758e5532b2996a7455a56dc30ca4a9d6 resolves #3
